// <auto-generated />
using System;
using DailyTask.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DailyTask.Infrastructure.Migrations
{
    [DbContext(typeof(DailyTaskDbContext))]
    [Migration("20260214031237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DAILYTASK")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyTask.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("PROJECTS", "DAILYTASK");
                });

            modelBuilder.Entity("DailyTask.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DUE_AT_UTC");

                    b.Property<bool>("IsDone")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IS_DONE");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("NOTES");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TASKS", "DAILYTASK");
                });

            modelBuilder.Entity("DailyTask.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("DailyTask.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DailyTask.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
